### PR TITLE
Use built-in typescript syntax in ST4

### PR DESCRIPTION
**Pull request by rchl**

### CODE REVIEW

**Comment by facelessuser** [comment]
Thanks!

@gir-bot lgtm

**Comment by rchl** [comment]
@facelessuser feeling like make it a release for it?

**Comment by facelessuser** [comment]
I do intend to. I'm knee-deep in some other projects right now. But I should get a release out for this by the end of month (give or take a few days).

**Comment by facelessuser** [comment]
I'm going to get this out for you today. Been doing too much open-source coding this weekend 🙃.

**Comment by facelessuser** [comment]
📦 released

**Pull request merged**
