### PR TITLE
remove: cmd and args

### PR DESCRIPTION
**Pull request by TheSecEng**
**Change Log: Sublime Text: 4074**
- API: Window.new_html_sheet() now accepts the sublime.ADD_TO_SELECTION flag
- API: Window.new_html_sheet() no longer accepts cmd and args parameters

**Fixes**

- [x] #82

### CODE REVIEW

**Comment by facelessuser** [comment]
So I assume that instead of cmd and arg the feature relies on subl links?

**Comment by jrappen** [comment]
I assume it forces the use `open_url`, prohibiting custom solutions.

**Comment by facelessuser** [comment]
Hmm that limits its use some. That kind of sucks. Oh well, it was probably provided for a very specific type of use case though.

**Comment by facelessuser** [comment]
@gir-bot lgtm

**Comment by jrappen** [comment]
@facelessuser I'd appreciate a new release with these changes.

@TheSecEng Thanks. Next time, GitHub requires `fixes #82` or `closes #82` on its own line for auto-close to work. Fancy readable layouts don't work.

**Comment by facelessuser** [comment]
Yeah, I need to just verify things a bit, prepare the changelog, etc. I'm also in the middle of a move and such, so hopefully today, but we'll see.

**Comment by jrappen** [comment]
No pressure.

**Comment by TheSecEng** [comment]
> @facelessuser I'd appreciate a new release with these changes.
> 
> @TheSecEng Thanks. Next time, GitHub requires `fixes #82` or `closes #82` on its own line for auto-close to work. Fancy readable layouts don't work.

Ahh always wondered how it works. Thanks!

**Comment by jrappen** [comment]
@TheSecEng compare:

* https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue
* as well as related to your style:
    * https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
    * https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular

**Comment by facelessuser** [comment]
In answer to my own question, you can use `subl:cmd` links. Not sure there is a way to pass arguments, but that is the best you get it seems.

**Comment by facelessuser** [comment]
Sounds like you can pass arbitrary arguments, I assume in string form so I'll have to evaluate how clever it is, but looks workable.

**Comment by jrappen** [comment]
I think Will said it's in the format `subl:cmd { "arg1": "val1", "arg2": "val2" }`.

**Comment by facelessuser** [comment]
Yup, so today's pretty good.

**Pull request merged**
